# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bootcamp Assignment 1 - Automation

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Installing Surge
      run: npm install --global surge
    - name: Deploying using surge
      run: surge ./ bootcamp2020_m_awais.surge.sh --token ${{ secrets.SURGE_TOKEN }}
