# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bootcamp Assignment 1 - Automation

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing Surge
      uses: npm install -g surge
    - name: Deploying using surge
      uses: surge ./ bootcamp2020_m_awais.surge.sh --token ${{ secrets.SURGE_TOKEN }}
